# Site settings
title: Will cars dream?
email: benjamin.tdm@gmail.com
description: This is a blog about self-driving cars.
baseurl: "/blog"
url: "http://benjamintd.github.io"
github_username: 

# Site settings
title: Zetsu
email: zetsu@domain.com
description: Um lindo tema feito para jekyll e com o <3
baseurl: "/zetsu"
url: "http://nandomoreira.me"

author:
  name     : 'Benjamin TD'
  email    : benjamin.tdm@gmail.com
  url      : http://benjamintd.github.io
  facebook : http://facebook.com/benjamin.td

github: https://github.com/benjamintd

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
